Company.G02.PL/Controllers/DepartmentsController.cs
using AutoMapper;
using Company.G02.BLL.Interfaces;
using Company.G02.BLL.Repositories;
using Company.G02.DAL.Models;
using Company.G02.PL.ViewModels.Departments;
using Company.G02.PL.ViewModels.Employees;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.G02.PL.Controllers
{
    [Authorize]
    public class DepartmentsController : Controller
    {
        private readonly IUnitOfwork unitOfwork;
        private readonly IMapper _mapper;

        public DepartmentsController(IUnitOfwork unitOfwork,IMapper mapper)
        {
            this.unitOfwork = unitOfwork;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var departments =await unitOfwork.DepartmentRepository.GetAllAsync();
            var Result = _mapper.Map<IEnumerable<DepartmentViewModel>>(departments);

            return View(Result);
        }


        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]

        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var department = _mapper.Map<Department>(model);

                unitOfwork.DepartmentRepository.Add(department);
                var count =await unitOfwork.SaveChangeAsync();
                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);


        }

        public async Task<IActionResult> Details(int? id , string viewName= "departments")
        {

            if (id is null) return BadRequest();
            var departments =await unitOfwork.DepartmentRepository.GetAsync(id.Value);

            if (departments is null)
            {
                return NotFound();
            }
            var departmentViewModel = _mapper.Map<DepartmentViewModel>(departments);

            return View(departmentViewModel);

        }

        [HttpGet]

        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null)
                {
                    return BadRequest();
                }

                var department = await unitOfwork.DepartmentRepository.GetAsync(id.Value);

                if (department is null)
                { return NotFound(); }

                var departmentViewModel = _mapper.Map<DepartmentViewModel>(department);

                return View(departmentViewModel);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
                    }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(DepartmentViewModel model, [FromRoute] int id)
        {

            if (model.Id !=id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {

                try
                {
                    var departments = _mapper.Map<Department>(model);
                     unitOfwork.DepartmentRepository.Update(departments);
                    var Count =await unitOfwork.SaveChangeAsync();

                    if (Count >0 )
                    {
                    return RedirectToAction(nameof(Index));

                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    return RedirectToAction("Error", "Home");
                }
            }
            return View(model);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id is null)
                {
                    return BadRequest();
                }

                var department = await unitOfwork.DepartmentRepository.GetAsync(id.Value);
                if (department is null)
                { return NotFound(); }
                var departmentViewModel = _mapper.Map<DepartmentViewModel>(department);

                return View(departmentViewModel);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }

        [ValidateAntiForgeryToken]

        [HttpPost]
        public async Task<IActionResult> Delete(DepartmentViewModel model, [FromRoute] int id)
        {
            if ((id != model.Id))
            {
                return BadRequest();
            }

            try
            {
                var departments = _mapper.Map<Department>(model);

                unitOfwork.DepartmentRepository.Delete(departments);
                var Count = await unitOfwork.SaveChangeAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(model);
        }

    }

}

Company.G02.PL/Controllers/EmployeesController.cs
using AutoMapper;
using Company.G02.BLL.Interfaces;
using Company.G02.DAL.Models;
using Company.G02.PL.Helper;
using Company.G02.PL.ViewModels.Employees;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.G02.PL.Controllers
{
	[Authorize]
	public class EmployeesController : Controller
    {
        private readonly IUnitOfwork _unitOfwork;
        private readonly IMapper _mapper;

        public EmployeesController(
                                    IUnitOfwork unitOfwork,
                                    IMapper mapper)
        {
            
            _unitOfwork = unitOfwork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string InputSearch)
        {
            var employees = Enumerable.Empty<Employee>();
            if (string.IsNullOrEmpty(InputSearch))
            {
                employees = await _unitOfwork.EmployeeRepository.GetAllAsync();

            }

            else
            {
                employees =await _unitOfwork.EmployeeRepository.GetByNameAsync(InputSearch);
            }

            var Result = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
   

            return View(Result);
        }
        public async Task<IActionResult> Search(string InputSearch)
        {
            var employees = Enumerable.Empty<Employee>();
            if (string.IsNullOrEmpty(InputSearch))
            {
                employees = await _unitOfwork.EmployeeRepository.GetAllAsync();

            }

            else
            {
                employees = await _unitOfwork.EmployeeRepository.GetByNameAsync(InputSearch);
            }

            var Result = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);


            return PartialView("PartialViews/EmployeeSearchPartialView", Result);
        }


        [HttpGet]

        public async Task<IActionResult> Create()
        {

            var departments = await _unitOfwork.DepartmentRepository.GetAllAsync();
            ViewData["departments"] = departments;
            return View();
        }

        [ValidateAntiForgeryToken]

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.ImageName = DecumentSettings.UplodeFile(model.Image, "Images");
                //var Employee = _mapper.Map<Employee>(model);

                var employee = _mapper.Map<Employee>(model);
                _unitOfwork.EmployeeRepository.Add(employee);
                var count = await _unitOfwork.SaveChangeAsync();
                if (count > 0)
                {
                    TempData["Message"] = "Employee Is Created";
                }
                else
                {
                    TempData["Message"] = "Employee Is Not Created";
                }
                return RedirectToAction("Index");
            }
            return View(model);


        }

        public async Task<IActionResult> Details(int? id, string viewName = "employee")
        {

            if (id is null) return BadRequest();
            var employee =await _unitOfwork.EmployeeRepository.GetAsync(id.Value);

            if (employee is null)
            {
                return NotFound();
            }

            var employeeViewModel = _mapper.Map<EmployeeViewModel>(employee);

            return View(employeeViewModel);

        }

        [HttpGet]

        public async Task<IActionResult> Edit(int? id)
        {
            //if (id is null)
            //{
            //    return BadRequest();
            //}

            //var department = _departmentRepository.Get(id.Value);
            //if (department is null)
            //{ return NotFound(); }
            //return View(department);
            try
            {
                var departments = await _unitOfwork.DepartmentRepository.GetAllAsync();
                ViewData["departments"] = departments;

                if (id is null) { return BadRequest(); }
                var employees = await _unitOfwork.EmployeeRepository.GetAsync(id.Value);
                if (employees is null) { return NotFound(); }
                var employeeViewModel = _mapper.Map<EmployeeViewModel>(employees);


                return View(employeeViewModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeViewModel model, [FromRoute] int id)
        {

            if (model.Id != id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {

               

                try
                {

                    if (model.ImageName is not null)
                    {
                        DecumentSettings.DeleteFile(model.ImageName, "Images");
                    }
                 model.ImageName=   DecumentSettings.UplodeFile(model.Image, "Images");

                    var employee = _mapper.Map<Employee>(model);

                    _unitOfwork.EmployeeRepository.Update(employee);
                    var Count =await _unitOfwork.SaveChangeAsync();
                    if (Count > 0)
                    {
                        TempData["Message"] = "Employee Is Updated";

                    }
                    else
                    {
                        TempData["Message"] = "Employee Is Updated";

                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(model);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            var employee =await _unitOfwork.EmployeeRepository.GetAsync(id.Value);
            if (employee is null)
            { return NotFound(); }


            var employeeViewModel = _mapper.Map<EmployeeViewModel>(employee);

            return View(employeeViewModel);


        }



        [ValidateAntiForgeryToken]

        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeViewModel model, [FromRoute] int id)
        {

            try
            {
                if ((id != model.Id))
                {
                    return BadRequest();
                }

                if (ModelState.IsValid)
                {

                    var employee = _mapper.Map<Employee>(model);

                    _unitOfwork.EmployeeRepository.Delete(employee);
                    var Count =await _unitOfwork.SaveChangeAsync();


                    if (Count > 0)
                    {
                        DecumentSettings.DeleteFile(model.ImageName, "Images");
                        return RedirectToAction(nameof(Index)); }

                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(model);
        }
    }
}

Company.G02.PL/Views/Shared/_AuthCheckPasswordLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Forget Password Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Custom Theme files -->
	<link href="~/css/_AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->




	<div class="wrapper">
		<div class="cardShadow">
			<div class="circle circle1"></div>
			<div class="block1">
				<div class="logo">
				</div>
				@RenderBody()
			</div>

		</div>
	</div>
	<!-- //main -->

</body>
</html>

Company.G02.PL/Views/Shared/_AuthForgetPasswordLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Forget Password Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Custom Theme files -->
	<link href="~/css/_AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />

	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->




	<div class="wrapper">
		<div class="cardShadow">
			<div class="circle circle1"></div>
			<div class="block1">
				<div class="logo">
					<h2>ForgetPassword</h2>
				</div>
				@RenderBody()
			</div>

		</div>
	</div>
	<!-- //main -->

</body>
</html>

Company.G02.PL/Views/Shared/_AuthResetPasswordLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Reset Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Custom Theme files -->
	<link href="~/css/_AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />

	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->




	<div class="wrapper">
		<div class="cardShadow">
			<div class="circle circle1"></div>
			<div class="block1">
				<div class="logo">
					<h1>Reset Password</h1>
				</div>
				@RenderBody()
			</div>

		</div>
	</div>
	<!-- //main -->

</body>
</html>

Company.G02.PL/Views/Shared/_AuthSingInLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>SignIn Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Custom Theme files -->
	<link href="~/css/_AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

	<!-- //web font -->
</head>
<body>
	<!-- main -->




	<div class="wrapper">
		<div class="cardShadow">
			<div class="circle circle1"></div>
			<div class="block1">
				<div class="logo">
					<h1>LOGIN</h1>
				</div>
			@RenderBody()
			</div>

		</div>
	</div>
	<!-- //main -->

</body>
</html>

Company.G02.PL/Views/Shared/_AuthSingUpLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Custom Theme files -->
	<link href="~/css/_AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />

	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
	<style>

		.wrapper .cardShadow .block1, .wrapper .cardShadow .block2 {
			width: 80%;
			height: 80%;
			box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.302);
			position: absolute;
			padding: 37px 30px;
			left: 50%;
			transform: translatex(-50%);
			top: 45px;
			border-radius: 15px;
			background: #fff;
		}
	</style>
</head>
<body>
	<!-- main -->




	<div class="wrapper">
		<div class="cardShadow">
			<div class="circle circle1"></div>

			<div class="block1">
				<div class="logo">
					<h1>Sign Up</h1>
				</div>
				@RenderBody()
			</div>

		</div>
	</div>
	<!-- //main -->

</body>
</html>

Company.G02.PL/Views/Shared/_BtnPartialView.cshtml
@model string



<td>
    <a asp-action="Details" asp-route-id="@Model" class="text-info">
        <i class="fas fa-eye"></i> 
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="text-warning">
        <i class="fas fa-edit"></i> 
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="text-danger">
        <i class="fas fa-trash"></i> 
    </a>
</td>

Company.G02.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.G02.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.G02.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.G02.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 text-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item me-2">
                                <a class="nav-link text-dark btn btn-outline-light" asp-area="" asp-controller="role" asp-action="Index">Roles</a>
                            </li>

                            <li class="nav-item me-2">
                                <a class="nav-link text-dark btn btn-outline-light" asp-area="" asp-controller="user" asp-action="Index">Users</a>
                            </li>
                        }



                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-outline-light" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.G02.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Validation", required: false)
</body>
</html>